#!/bin/sh

if [ ! -x /etc/init.d/network-manager ]; then
    exit 0
fi

case $1 in
    startup)
	service NetworkManager stop || true
    ;;
    cleanup)
	service NetworkManager start || true
    ;;
esac
