#!/bin/sh

# Allow PasswordAuthentification in sshd config
sed -i -e 's|\(PasswordAuthentication\) no|\1 yes|' /etc/ssh/sshd_config

# Do not allow root login without password
sed -i -e 's|\(PermitRootLogin\) without-password|\1 yes|' /etc/ssh/sshd_config
