#!/bin/sh

set -e

# Remove live user (if any) from firejail authorizations
in-target sh -c 'sed -i "/user/d" /etc/firejail/firejail.users'

# Authorize new user
in-target sh -c 'ls /home/ >> /etc/firejail/firejail.users'
