#!/bin/sh

if grep -qw persistence /proc/cmdline; then
    # With persistence enabled, don't modify the configuration, let the
    # user be in charge...
    exit 0
fi

# Allow PasswordAuthentification in sshd config
sed -i -e 's|#\?\(PasswordAuthentication\) no|\1 yes|' /etc/ssh/sshd_config
